### ISSUE TITLE
手动滑动很费劲

### ISSUE THREAD

**Issue by Lyang166** [leveychen/RxBanner#2]
必须要滑动很长距离才可以

**Comment by leveychen** [comment]
默认是一半的屏幕，可以调整滑动速度，未来将增加滑动的屏幕比例设定

`rb_itemMoveSpeed`

**Comment by jackzhouguilong** [comment]
期待优化，看好这个库

**Comment by leveychen** [comment]
已修复，参考 release [1.1.0](https://github.com/leveychen/RxBanner/releases/tag/1.1.0)  发布信息
