### ISSUE TITLE
指示器的图标可以替换成资源文件吗?

### ISSUE THREAD

**Issue by zofnk** [leveychen/RxBanner#3]
指示器的图标可以替换成资源文件吗?或者网络图片

**Comment by leveychen** [comment]
默认指示器是绘制出来的，默认的指示器是不支持替换图片的，因为带有动画效果。你可以采用其他指示器，然后绑定到这个banner上即可。 改天写个demo

**Comment by zofnk** [comment]
ReadMe里写的那个CircleIndicator,是要怎么绑定到banner , 覆盖在banner布局上吗还是为子布局...
还是在banner.bulid 里 new CircleIndicator() ?

**Comment by leveychen** [comment]
已新增自定义指示器
参考 release [1.1.0](https://github.com/leveychen/RxBanner/releases/tag/1.1.0)  发布信息 
用法自行在Readme查看
