### ISSUE TITLE
依赖出错

### ISSUE THREAD

**Issue by zofnk** [leveychen/RxBanner#4]
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"C:\\Users\\admin\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc02.aar\\79841d6aba93adaefc26e3e63089b3fc\\res\\values-v28\\values-v28.xml","position":{"startLine":8,"startColumn":4,"startOffset":447,"endLine":11,"endColumn":12,"endOffset":684}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/dialogCornerRadius not found.","sources":[{"file":"D:\\Project\\MyDemo\\app\\build\\intermediates\\incremental\\mergeDebugResources\\merged.dir\\values-v28\\values-v28.xml","position":{"startLine":10}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/fontVariationSettings not found.","sources":[{"file":"C:\\Users\\admin\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc02.aar\\79841d6aba93adaefc26e3e63089b3fc\\res\\values\\values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}
AGPBI: {"kind":"error","text":"error: resource android:attr/ttcIndex not found.","sources":[{"file":"C:\\Users\\admin\\.gradle\\caches\\transforms-1\\files-1.1\\appcompat-v7-28.0.0-rc02.aar\\79841d6aba93adaefc26e3e63089b3fc\\res\\values\\values.xml","position":{"startLine":1303,"startColumn":4,"startOffset":70911,"endColumn":68,"endOffset":70975}}],"original":"","tool":"AAPT"}

你的appcompat版本是28...?

**Comment by leveychen** [comment]
是的， 28 的 target 与 4.10 的Gradle

**Comment by zofnk** [comment]
能降下来吗? 我的是27 依赖后build就会出现上述的错误...

**Comment by leveychen** [comment]
在 app.gradle 最下面添加

````
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                //这里指定需要统一的依赖版本,这里统一为27.1.1
                details.useVersion '27.1.1'
            }
        }
    }
}
````
强制使用你的主项目的 版本

**Comment by zofnk** [comment]
好的 谢谢..
可以再banner只有一页的时候 直接不能滑动吗? 现在是可以滑动 但是滑不过去...

**Comment by leveychen** [comment]
1.1.2新增了 `rb_canSwipeWhenSingle` 可以满足你的需求
