### ISSUE TITLE
RxBannerEmptyView 可否提供设置ImageView的scaleType?

### ISSUE THREAD

**Issue by zofnk** [leveychen/RxBanner#6]
url为空的时候设置空的占位图 , 可以再多条ImageView的scaleType么

**Comment by zofnk** [comment]
Banner图片为2张的时候 , 第二张不能从右至左滑动到第一张

**Comment by leveychen** [comment]
EmptyView其实一般不推荐使用，推荐构造你们自己的业务需求占位图来充当EmptyView。这样整体图片样式可以与宿主一致。
